spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/itinerary-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect


